### ISSUE TITLE
Right clicking on a loaded shulker deletes first stack

### ISSUE THREAD

**Issue by xR4YM0ND** [Fuzss/easyshulkerboxes-fabric#1] opened 2022-04-18 19:07 UTC
So when the shulker box is in your inventory and you hover over it and right click -> the first stack gets deleted

Fabric 1.18.2 - 0.13.3 
newest EasyShulkerBoxes

**Comment by Fuzss** [comment] 2022-04-18 22:43
Do you have the Charm mod installed?

**Comment by xR4YM0ND** [comment] 2022-04-19 10:34
yes, but i have set all shulker related configs to false on the server ( not the client ) -> now i can duplicate items and some items get lost

then i have set to configs to false on the client too -> now it semi works, sometimes items get lost and i can duplicate as well

**Comment by xR4YM0ND** [comment] 2022-04-19 10:35
I have a lot of mods in there btw

**Comment by xR4YM0ND** [comment] 2022-04-19 10:35
i can show you on discord if you want: SpigotDE#8841

**Comment by Fuzss** [comment] 2022-04-20 07:02
Does the issue also happen when only Easy Shulker Boxes is installed?
Is this similar to the issue you’re having? https://github.com/LunaPixelStudios/Better-Minecraft/issues/216
Which Charm options specifically did you disable?
I‘m not on discord for the next week. Would be great if you could record a short clip if we can’t figure out the issue otherwise.

**Comment by Fuzss** [comment] 2022-07-10 07:10
Did a few more tests and I'm not able to reproduce this with just my mod, only when Charm is installed issues do arise if the config is not set properly. Therefore closing this now.

**Closed as completed by Fuzss** 2022-07-10 07:10 UTC
